---
- name: Telegram | Alerts Block
  block:
    - name: Telegram | Send failure alert
      community.general.telegram:
        token: "{{ telegram_token }}"
        api_args:
          chat_id: "{{ telegram_chat_id }}"
          parse_mode: "markdown"
          text: "⚠️  Ansible Provisioning Failed on *{{ ansible_hostname }}*\n\n
            🛠️ *Task*:  {{ ansible_failed_task.name }}\n
            🎬 *Action*: {{ ansible_failed_task.action }}\n
            ❌ *Error Message*: \n ```{{ ansible_failed_result | to_nice_json }}```"
      changed_when: false

  rescue:
    - name: Telegram | Send failure alert
      community.general.telegram:
        token: "{{ telegram_token }}"
        api_args:
          chat_id: "{{ telegram_chat_id }}"
          parse_mode: "markdown"
          text: "⚠️  Ansible Provisioning Failed on *{{ ansible_hostname }}*\n\n
            Check the log for details."
      changed_when: false
