---
registry_url: "{{ lookup('env', 'REGISTRY_URL') | default('https://index.docker.io/v1/', true) }}"
docker_username: "{{ lookup('env', 'DOCKER_USERNAME') | default(false)}}"
docker_pass: "{{ lookup('env', 'DOCKER_PASS') | default(true) }}"
docker_image: "{{ lookup('env', 'DOCKER_IMAGE') | default('nginxdemos/hello', true) }}"
