---
registry_url: "{{ lookup('env', 'REGISTRY_URL') }}"
docker_username: "{{ lookup('env', 'DOCKER_USERNAME') }}"
docker_pass: "{{ lookup('env', 'DOCKER_PASS') }}"
docker_image: "{{ lookup('env', 'DOCKER_IMAGE') }}"
