---
- name: Deployment | Include Distro Variables
  ansible.builtin.include_vars: "{{ ansible_distribution }}.yml"
  tags: always

- name: Deployment | Include Role Variables
  ansible.builtin.include_vars: "../../pre-configure/vars/main.yml"
  tags: always

- name: Deployment
  become: true
  become_user: "{{ custom_user }}"
  block:
    - name: "Verify that required string variables are defined"
      assert:
        that:
          - "{{ item.var }} is defined"
          - "{{ item.var }} | length > 0"
          - "{{ item.var }} != None"
        fail_msg: "{{ item.var }} needs to be set for the role to work"
        success_msg: "Required variable {{ item.var }} is defined"
      with_items:
        - { var: "{{ docker_username }}" }
        - { var: "{{ docker_pass }}" }
    - name: Deployment | Deploying Docker
      ansible.builtin.import_tasks: application/app.yml

  rescue:
    - name: Deployment | Rescue
      ansible.builtin.set_fact:
        task_failed: true
